### ISSUE TITLE
no `init` task, as describe in readme

### ISSUE THREAD

**Issue by silky** [hasktorch/hasktorch#118]
i can't do `make init`, even though the readme says i should be able to

**Comment by austinvhuang** [comment]
Hi @silky, thanks for the note, it had gotten out of date with the repo structure. I added one back an init target that does the following:

- builds aten
- copies appropriate cabal freeze file depending on your ghc version (in a perfect world everyone has nix, but that's not a reasonable expectation)
- creates a local cabal project file. This replaces the README instructions requiring environment variables pointing to the aten shared library since it automatically points to the path where aten is built
- updates cabal

Thanks for trying this out, feel free to reach out if you still run into issues. Can also contact us via AUTHORS - would be happy to add you to the slack channel.
