### ISSUE TITLE
Named tensor indices

### ISSUE THREAD

**Issue by Saulzar** [hasktorch/hasktorch#138]
Could this simplify statically typed tensor sizes quite a bit?

http://nlp.seas.harvard.edu/NamedTensor?fbclid=IwAR2JHRK5zFuqpCHKDDcpYsmx0IoLmjaaYnzim6uSEiW1iHBfScpqjs0HiTk

**Comment by stites** [comment]
The static interface subsumes this work with a caveat around broadcasting possibly best represented as Naperian Functors (Austin and I actually just met with Sasha yesterday and chatted about namedtensor and hasktorch). We floated the idea of having a repo which generates our static-interface (sort of like [haskell-backpack/backpack-str](https://github.com/haskell-backpack/backpack-str)). Ideally we generate the interface from some yaml-esq spec so that the python folks can make use of it (also so that we can get more eyes/contributions/concensus).
 
I've sent you an invite to the slack channel (I was supposed to do this before from reddit release but the holidays were loaded with travel). I just used your public email on github -- heads-up! Happy to discuss this further, but I'm going to close this issue for now.
