### ISSUE TITLE
add raw bindings for THNN

### ISSUE THREAD

**Issue by stites** [hasktorch/hasktorch#63]

**Comment by AlejandroCatalina** [comment]
I've been working on this and I think I've made some progress. I note a few things regarding the code generator and THNN:

1. It iterates by default through all generic types, generating code for all generic types. I am not sure whether this is also the case for THNN or not. We should note that this module has a different structure as the others (it has a single THNN.h, whilst the others have THDouble.h, THFloat.h, etc, and many .c files). I am not sure about this so I have generated the bindings in a similar way to the others. If anyone knows more about this, great, I'll keep searching tho.
2. I've only worked so far on THNN (THCUNN is very similar, with new types).
3. I needed to add many new types to the generator to parse. Please check whether the style and place of the additions is okay.

You can see the commit in 4be23293b8d3d607670f16fcc5916133cc6b78d0 . If you like the work so far (it is still wrong in so many ways, but I think it may be a work in progress in the right direction) and any of you has the time to help me out I can make a WIP PR so that everybody may help (probably @austinvhuang ?)

In any case, I will keep working on this as I discover new things about the THNN module (it would be quite useful to start preparing some NN bindings, in the end is what everyone looks for).

Have I forgotten anything important? Do you have any useful pointers? Is this just wrong and I should remove the branch and move on to other things?

**Comment by stites** [comment]
@o1lo01ol1o  -- you might be interested in some of the output files as well.

**Comment by AlejandroCatalina** [comment]
THNN bindings address in #65.

**Comment by stites** [comment]
closing this and opening up a new ticket for THCUNN bindings
