### ISSUE TITLE
Write the "Deep Learning with Torch: the 60-minute blitz" tutorial

### ISSUE THREAD

**Issue by AlejandroCatalina** [hasktorch/hasktorch#64]
We should probably start writing the [Deep Learning with Torch: the 60-minute blitz tutorial](https://github.com/soumith/cvpr2015/blob/master/Deep%20Learning%20with%20Torch.ipynb) for the haskorch bindings, which would be a good first step to familiarise with the basic stuff.

**Comment by stites** [comment]
The start of this lives at: https://github.com/hasktorch/hasktorch/blob/master/examples/convolutions/LeNet.hs

**Comment by adamwespiser** [comment]
@stites the link you provided is dead!

**Comment by stites** [comment]
@adamwespiser thanks for taking note! I'm actively working on this example -- it requires some heavy internal modification due to some poor assumptions about how PyTorch optimizations interact with  [_backprop_](https://hackage.haskell.org/package/backprop).

The original examples have migrated into the following:
- [Main training loop](https://github.com/hasktorch/hasktorch/blob/master/examples/lenet-cifar10/Main.hs) -- just some loops for running epochs, batches (one-batches, in this case), and reporting output.
- [Architecture definition of LeNet](https://github.com/hasktorch/hasktorch/blob/master/zoo/src/Torch/Models/LeNet.hs) -- includes backprop'd instances which are giving me a little trouble.
- [Data loader for CIFAR-10](https://github.com/hasktorch/hasktorch/blob/master/zoo/src/Torch/Data/Loaders/Cifar10.hs) -- this could use some work and refactoring, ATM it's just single-threaded. This snapshot is also pretty messy.

**Comment by austinvhuang** [comment]
Will be writing up tutorials for the 0.2 release, but let's break that up into individual separate issues per tutorial.
